name: culinary_fusion
description: "Culinary Fusion - Merge, Cook, Discover. Un juego de fusión y cocina sin presión."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  uuid: ^4.4.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ingredients/
    - assets/images/recipes/
    - assets/images/customers/
    - assets/images/decorations/

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/appicon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/appicon.png"
  min_sdk_android: 21